name: recipes_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  equatable: ^2.0.5

  dartz: ^0.10.1

  dio: ^5.4.3+1

  pretty_dio_logger: ^1.3.1


  connectivity_plus: ^6.0.3

  floor: ^1.4.2

  sqflite: ^2.3.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

  floor_generator: any
  build_runner: any


flutter:

  uses-material-design: true